/** ISO 3166-1 alpha-2 codes (+ GB regional) for flagcdn.com */
const TEAM_TO_CODE: Record<string, string> = {
    Albania: "al",
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    Bolivia: "bo",
    "Bosnia & Herzegovina": "ba",
    Brazil: "br",
    Cameroon: "cm",
    Canada: "ca",
    "Cape Verde": "cv",
    Chile: "cl",
    Colombia: "co",
    "Costa Rica": "cr",
    Croatia: "hr",
    "Curaçao": "cw",
    Curacao: "cw",
    "Czech Republic": "cz",
    Czechia: "cz",
    Denmark: "dk",
    "DR Congo": "cd",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    Finland: "fi",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Greece: "gr",
    Haiti: "ht",
    Honduras: "hn",
    Hungary: "hu",
    Indonesia: "id",
    Iran: "ir",
    Iraq: "iq",
    Ireland: "ie",
    Israel: "il",
    "Ivory Coast": "ci",
    Jamaica: "jm",
    Japan: "jp",
    Jordan: "jo",
    Kenya: "ke",
    Mali: "ml",
    Mexico: "mx",
    Montenegro: "me",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Nigeria: "ng",
    "Northern Ireland": "gb-nir",
    "North Macedonia": "mk",
    Norway: "no",
    Panama: "pa",
    Paraguay: "py",
    Peru: "pe",
    Poland: "pl",
    Portugal: "pt",
    Qatar: "qa",
    Romania: "ro",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    Serbia: "rs",
    Slovakia: "sk",
    Slovenia: "si",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tanzania: "tz",
    "Trinidad and Tobago": "tt",
    "Trinidad & Tobago": "tt",
    Tunisia: "tn",
    Turkey: "tr",
    Türkiye: "tr",
    Ukraine: "ua",
    "United States": "us",
    USA: "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
    Venezuela: "ve",
    Wales: "gb-wls",
    Zimbabwe: "zw",
};

/**
 * apifootball-specific aliases that differ from standard names.
 * Key = what apifootball sends → canonical name used in TEAM_TO_CODE above.
 */
const APIFOOTBALL_ALIASES: Record<string, string> = {
    "korea republic":          "South Korea",
    "korea rep.":              "South Korea",
    "republic of korea":       "South Korea",
    "cote d'ivoire":           "Ivory Coast",
    "côte d'ivoire":           "Ivory Coast",
    "cote d`ivoire":           "Ivory Coast",
    "côte d’ivoire": "Ivory Coast",
    "ivory coast":             "Ivory Coast",
    "turkiye":                 "Turkey",
    "türkiye":                 "Turkey",
    "bosnia and herzegovina":  "Bosnia & Herzegovina",
    "bosnia herzegovina":      "Bosnia & Herzegovina",
    "bosnia":                  "Bosnia & Herzegovina",
    "dr congo":                "DR Congo",
    "congo dr":                "DR Congo",
    "democratic republic of the congo": "DR Congo",
    "democratic republic congo": "DR Congo",
    "trinidad and tobago":     "Trinidad and Tobago",
    "trinidad & tobago":       "Trinidad and Tobago",
    "trinidad tobago":         "Trinidad and Tobago",
    "usa":                     "United States",
    "united states":           "United States",
    "curacao":                 "Curaçao",
    "new zealand":             "New Zealand",
    "saudi arabia":            "Saudi Arabia",
    "south africa":            "South Africa",
    "south korea":             "South Korea",
    "north macedonia":         "North Macedonia",
    "republic of ireland":     "Ireland",
    "czech republic":          "Czech Republic",
    "cape verde":              "Cape Verde",
    "costa rica":              "Costa Rica",
    "burkina faso":            "Burkina Faso",
};

// Extra entries not in the main map (filled after alias resolution)
const EXTRA_CODES: Record<string, string> = {
    "Burkina Faso": "bf",
};

/** Resolve an apifootball team name → canonical name */
function resolve(name: string): string {
    const lower = name.toLowerCase().trim();
    return APIFOOTBALL_ALIASES[lower] ?? name;
}

/** Polish team name translations */
const TEAM_TO_PL: Record<string, string> = {
    Albania: "Albania",
    Algeria: "Algieria",
    Argentina: "Argentyna",
    Australia: "Australia",
    Austria: "Austria",
    Belgium: "Belgia",
    Bolivia: "Boliwia",
    "Bosnia & Herzegovina": "Bośnia i Hercegowina",
    Brazil: "Brazylia",
    "Burkina Faso": "Burkina Faso",
    Cameroon: "Kamerun",
    Canada: "Kanada",
    "Cape Verde": "Wyspy Zielonego Przylądka",
    Chile: "Chile",
    Colombia: "Kolumbia",
    "Costa Rica": "Kostaryka",
    Croatia: "Chorwacja",
    "Curaçao": "Curaçao",
    "Czech Republic": "Czechy",
    Denmark: "Dania",
    "DR Congo": "DR Kongo",
    Ecuador: "Ekwador",
    Egypt: "Egipt",
    England: "Anglia",
    Finland: "Finlandia",
    France: "Francja",
    Germany: "Niemcy",
    Ghana: "Ghana",
    Greece: "Grecja",
    Haiti: "Haiti",
    Honduras: "Honduras",
    Hungary: "Węgry",
    Indonesia: "Indonezja",
    Iran: "Iran",
    Iraq: "Irak",
    Ireland: "Irlandia",
    Israel: "Izrael",
    "Ivory Coast": "Wybrzeże Kości Słoniowej",
    Jamaica: "Jamajka",
    Japan: "Japonia",
    Jordan: "Jordania",
    Kenya: "Kenia",
    Mali: "Mali",
    Mexico: "Meksyk",
    Montenegro: "Czarnogóra",
    Morocco: "Maroko",
    Netherlands: "Holandia",
    "New Zealand": "Nowa Zelandia",
    Nigeria: "Nigeria",
    "Northern Ireland": "Irlandia Płn.",
    "North Macedonia": "Macedonia Płn.",
    Norway: "Norwegia",
    Panama: "Panama",
    Paraguay: "Paragwaj",
    Peru: "Peru",
    Poland: "Polska",
    Portugal: "Portugalia",
    Qatar: "Katar",
    Romania: "Rumunia",
    "Saudi Arabia": "Arabia Saudyjska",
    Scotland: "Szkocja",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Slovakia: "Słowacja",
    Slovenia: "Słowenia",
    "South Africa": "RPA",
    "South Korea": "Korea Płd.",
    Spain: "Hiszpania",
    Sweden: "Szwecja",
    Switzerland: "Szwajcaria",
    Tanzania: "Tanzania",
    "Trinidad and Tobago": "Trynidad i Tobago",
    Tunisia: "Tunezja",
    Turkey: "Turcja",
    Ukraine: "Ukraina",
    "United States": "USA",
    Uruguay: "Urugwaj",
    Uzbekistan: "Uzbekistan",
    Venezuela: "Wenezuela",
    Wales: "Walia",
    Zimbabwe: "Zimbabwe",
};

export function getFlagUrl(teamName: string): string | null {
    const canonical = resolve(teamName);
    const code = TEAM_TO_CODE[canonical] ?? EXTRA_CODES[canonical];
    if (!code) return null;
    // flagcdn.com — supports all ISO 3166-1 alpha-2 + regional (gb-eng, gb-sct, cw …)
    return `https://flagcdn.com/w80/${code}.png`;
}

export function getTeamNamePl(teamName: string): string {
    const canonical = resolve(teamName);
    return TEAM_TO_PL[canonical] ?? teamName;
}
