const TEAM_TO_CODE: Record<string, string> = {
    Albania: "al",
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    Bolivia: "bo",
    "Bosnia & Herzegovina": "ba",
    Brazil: "br",
    Cameroon: "cm",
    Canada: "ca",
    "Cape Verde": "cv",
    Chile: "cl",
    Colombia: "co",
    "Costa Rica": "cr",
    Croatia: "hr",
    "Curaçao": "cw",
    "Czech Republic": "cz",
    Denmark: "dk",
    "DR Congo": "cd",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    Finland: "fi",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Greece: "gr",
    Haiti: "ht",
    Honduras: "hn",
    Hungary: "hu",
    Indonesia: "id",
    Iran: "ir",
    Iraq: "iq",
    Israel: "il",
    "Ivory Coast": "ci",
    Jamaica: "jm",
    Japan: "jp",
    Jordan: "jo",
    Kenya: "ke",
    Mali: "ml",
    Mexico: "mx",
    Montenegro: "me",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Nigeria: "ng",
    Norway: "no",
    Panama: "pa",
    Paraguay: "py",
    Peru: "pe",
    Poland: "pl",
    Portugal: "pt",
    Qatar: "qa",
    Romania: "ro",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    Serbia: "rs",
    Slovakia: "sk",
    Slovenia: "si",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tanzania: "tz",
    Tunisia: "tn",
    Turkey: "tr",
    Ukraine: "ua",
    "United States": "us",
    USA: "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
    Venezuela: "ve",
    Wales: "gb-wls",
    Zimbabwe: "zw",
};

const TEAM_TO_PL: Record<string, string> = {
    Albania: "Albania",
    Algeria: "Algieria",
    Argentina: "Argentyna",
    Australia: "Australia",
    Austria: "Austria",
    Belgium: "Belgia",
    Bolivia: "Boliwia",
    "Bosnia & Herzegovina": "Bośnia i Hercegowina",
    Brazil: "Brazylia",
    Cameroon: "Kamerun",
    Canada: "Kanada",
    "Cape Verde": "Wyspy Zielonego Przylądka",
    Chile: "Chile",
    Colombia: "Kolumbia",
    "Costa Rica": "Kostaryka",
    Croatia: "Chorwacja",
    "Curaçao": "Curaçao",
    "Czech Republic": "Czechy",
    Denmark: "Dania",
    "DR Congo": "DR Kongo",
    Ecuador: "Ekwador",
    Egypt: "Egipt",
    England: "Anglia",
    Finland: "Finlandia",
    France: "Francja",
    Germany: "Niemcy",
    Ghana: "Ghana",
    Greece: "Grecja",
    Haiti: "Haiti",
    Honduras: "Honduras",
    Hungary: "Węgry",
    Indonesia: "Indonezja",
    Iran: "Iran",
    Iraq: "Irak",
    Israel: "Izrael",
    "Ivory Coast": "Wybrzeże Kości Słoniowej",
    Jamaica: "Jamajka",
    Japan: "Japonia",
    Jordan: "Jordania",
    Kenya: "Kenia",
    Mali: "Mali",
    Mexico: "Meksyk",
    Montenegro: "Czarnogóra",
    Morocco: "Maroko",
    Netherlands: "Holandia",
    "New Zealand": "Nowa Zelandia",
    Nigeria: "Nigeria",
    Norway: "Norwegia",
    Panama: "Panama",
    Paraguay: "Paragwaj",
    Peru: "Peru",
    Poland: "Polska",
    Portugal: "Portugalia",
    Qatar: "Katar",
    Romania: "Rumunia",
    "Saudi Arabia": "Arabia Saudyjska",
    Scotland: "Szkocja",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Slovakia: "Słowacja",
    Slovenia: "Słowenia",
    "South Africa": "RPA",
    "South Korea": "Korea Płd.",
    Spain: "Hiszpania",
    Sweden: "Szwecja",
    Switzerland: "Szwajcaria",
    Tanzania: "Tanzania",
    Tunisia: "Tunezja",
    Turkey: "Turcja",
    Ukraine: "Ukraina",
    "United States": "USA",
    USA: "USA",
    Uruguay: "Urugwaj",
    Uzbekistan: "Uzbekistan",
    Venezuela: "Wenezuela",
    Wales: "Walia",
    Zimbabwe: "Zimbabwe",
};

export function getFlagUrl(teamName: string): string | null {
    const code = TEAM_TO_CODE[teamName];
    if (!code) return null;
    return `https://cdn.jsdelivr.net/gh/kapowaz/square-flags@master/flags/${code}.svg`;
}

export function getTeamNamePl(teamName: string): string {
    return TEAM_TO_PL[teamName] ?? teamName;
}
