/**
 * Static fallback venue map: normalised team name → stadium string.
 * Used when apifootball.com doesn't return match_stadium.
 */
export const STADIUM_MAP: Record<string, string> = {
    // ── Premier League ─────────────────────────────────────────────
    "arsenal": "Emirates Stadium, London",
    "aston villa": "Villa Park, Birmingham",
    "bournemouth": "Vitality Stadium, Bournemouth",
    "brentford": "Gtech Community Stadium, London",
    "brighton": "American Express Stadium, Brighton",
    "brighton and hove albion": "American Express Stadium, Brighton",
    "chelsea": "Stamford Bridge, London",
    "crystal palace": "Selhurst Park, London",
    "everton": "Goodison Park, Liverpool",
    "fulham": "Craven Cottage, London",
    "ipswich": "Portman Road, Ipswich",
    "ipswich town": "Portman Road, Ipswich",
    "leeds": "Elland Road, Leeds",
    "leeds united": "Elland Road, Leeds",
    "leicester": "King Power Stadium, Leicester",
    "leicester city": "King Power Stadium, Leicester",
    "liverpool": "Anfield, Liverpool",
    "manchester city": "Etihad Stadium, Manchester",
    "manchester united": "Old Trafford, Manchester",
    "newcastle": "St. James' Park, Newcastle",
    "newcastle united": "St. James' Park, Newcastle",
    "nottingham forest": "City Ground, Nottingham",
    "southampton": "St Mary's Stadium, Southampton",
    "tottenham": "Tottenham Hotspur Stadium, London",
    "tottenham hotspur": "Tottenham Hotspur Stadium, London",
    "west ham": "London Stadium, London",
    "west ham united": "London Stadium, London",
    "wolverhampton": "Molineux Stadium, Wolverhampton",
    "wolverhampton wanderers": "Molineux Stadium, Wolverhampton",
    "wolves": "Molineux Stadium, Wolverhampton",
    // ── Serie A ────────────────────────────────────────────────────
    "ac milan": "San Siro, Milan",
    "milan": "San Siro, Milan",
    "inter": "San Siro, Milan",
    "internazionale": "San Siro, Milan",
    "inter milan": "San Siro, Milan",
    "juventus": "Allianz Stadium, Turin",
    "napoli": "Stadio Diego Armando Maradona, Naples",
    "roma": "Stadio Olimpico, Rome",
    "lazio": "Stadio Olimpico, Rome",
    "fiorentina": "Stadio Artemio Franchi, Florence",
    "atalanta": "Gewiss Stadium, Bergamo",
    "torino": "Stadio Olimpico Grande Torino, Turin",
    "bologna": "Stadio Renato Dall'Ara, Bologna",
    "udinese": "Dacia Arena, Udine",
    "genoa": "Stadio Luigi Ferraris, Genoa",
    "parma": "Stadio Ennio Tardini, Parma",
    "sassuolo": "MAPEI Stadium, Reggio Emilia",
    "cagliari": "Unipol Domus, Cagliari",
    "verona": "Stadio Marcantonio Bentegodi, Verona",
    "hellas verona": "Stadio Marcantonio Bentegodi, Verona",
    "lecce": "Stadio Via del Mare, Lecce",
    "empoli": "Stadio Carlo Castellani, Empoli",
    "monza": "Stadio Brianteo, Monza",
    "frosinone": "Stadio Benito Stirpe, Frosinone",
    "salernitana": "Stadio Arechi, Salerno",
    // ── La Liga ────────────────────────────────────────────────────
    "real madrid": "Santiago Bernabéu, Madrid",
    "barcelona": "Estadi Olímpic Lluís Companys, Barcelona",
    "atletico madrid": "Cívitas Metropolitano, Madrid",
    "sevilla": "Estadio Ramón Sánchez-Pizjuán, Sevilla",
    "real sociedad": "Reale Arena, San Sebastián",
    "real betis": "Estadio Benito Villamarín, Sevilla",
    "athletic bilbao": "San Mamés, Bilbao",
    "athletic club": "San Mamés, Bilbao",
    "villarreal": "Estadio de la Cerámica, Villarreal",
    "valencia": "Estadio de Mestalla, Valencia",
    "girona": "Estadio Municipal de Montilivi, Girona",
    "osasuna": "El Sadar, Pamplona",
    "mallorca": "Visit Mallorca Estadi, Palma",
    "getafe": "Coliseum Alfonso Pérez, Getafe",
    "celta vigo": "Abanca-Balaídos, Vigo",
    "rayo vallecano": "Estadio de Vallecas, Madrid",
    "alaves": "Mendizorroza, Vitoria-Gasteiz",
    "deportivo alaves": "Mendizorroza, Vitoria-Gasteiz",
    "granada": "Estadio Nuevo Los Cármenes, Granada",
    "almeria": "Power Horse Stadium, Almería",
    "cadiz": "Estadio Ramón de Carranza, Cádiz",
    "las palmas": "Estadio Gran Canaria, Las Palmas",
    "leganes": "Estadio Municipal de Butarque, Leganés",
    "espanyol": "RCDE Stadium, Cornellà de Llobregat",
    // ── Ligue 1 ────────────────────────────────────────────────────
    "paris saint-germain": "Parc des Princes, Paris",
    "psg": "Parc des Princes, Paris",
    "marseille": "Orange Vélodrome, Marseille",
    "lyon": "Groupama Stadium, Décines-Charpieu",
    "olympique lyonnais": "Groupama Stadium, Décines-Charpieu",
    "monaco": "Stade Louis II, Monaco",
    "as monaco": "Stade Louis II, Monaco",
    "lille": "Stade Pierre-Mauroy, Villeneuve-d'Ascq",
    "losc lille": "Stade Pierre-Mauroy, Villeneuve-d'Ascq",
    "lens": "Stade Bollaert-Delelis, Lens",
    "rc lens": "Stade Bollaert-Delelis, Lens",
    "rennes": "Roazhon Park, Rennes",
    "stade rennais": "Roazhon Park, Rennes",
    "nice": "Allianz Riviera, Nice",
    "ogc nice": "Allianz Riviera, Nice",
    "strasbourg": "Stade de la Meinau, Strasbourg",
    "nantes": "Stade de la Beaujoire, Nantes",
    "montpellier": "Stade de la Mosson, Montpellier",
    "brest": "Stade Francis-Le Blé, Brest",
    "toulouse": "Stadium de Toulouse, Toulouse",
    "reims": "Stade Auguste-Delaune, Reims",
    "stade de reims": "Stade Auguste-Delaune, Reims",
    "lorient": "Stade du Moustoir, Lorient",
    "metz": "Stade Saint-Symphorien, Metz",
    "clermont": "Stade Gabriel-Montpied, Clermont-Ferrand",
    "le havre": "Stade Océane, Le Havre",
    "maccabi tel aviv": "Bloomfield Stadium, Tel Aviv",
    // ── Ekstraklasa ────────────────────────────────────────────────
    "legia warszawa": "Stadion Legia, Warszawa",
    "lech poznan": "INEA Stadion, Poznań",
    "jagiellonia bialystok": "Stadion Miejski, Białystok",
    "rakow czestochowa": "Stadion Miejski, Częstochowa",
    "pogon szczecin": "Stadion Florian Krygier, Szczecin",
    "cracovia": "Stadion im. J. Piłsudskiego, Kraków",
    "gornik zabrze": "Stadion im. E. Pohla, Zabrze",
    "wisla plock": "Stadion Wisły Płock, Płock",
    "zaglebie lubin": "Stadion Zagłębia, Lubin",
    "piast gliwice": "Stadion Piasta, Gliwice",
    "slask wroclaw": "Tarczyński Arena, Wrocław",
    "widzew lodz": "Stadion Widzewa, Łódź",
    "gks katowice": "Stadion GKS Katowice, Katowice",
    "motor lublin": "Stadion Motoru, Lublin",
    "arka gdynia": "Stadion im. Z. Krzyszkowiaka, Gdynia",
    "lechia gdansk": "Polsat Plus Arena Gdańsk, Gdańsk",
    "korona kielce": "Suzuki Arena, Kielce",
    "radomiak radom": "Stadion Radomiaka, Radom",
};

function normKey(s: string) {
    return s
        .normalize("NFD")
        .replace(/[̀-ͯ]/g, "")
        .replace(/[łŁ]/g, "l")
        .replace(/\s*&\s*/g, " and ")
        .toLowerCase()
        .trim();
}

export function getStadium(homeTeam: string): string | null {
    return STADIUM_MAP[normKey(homeTeam)] ?? null;
}
