name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_t84KFFIcwuSSYWAyNwld2YNK
          VERCEL_PROJECT_ID: prj_aJY2Emu2Hw009sksShO5XxH2crFY
        run: vercel deploy --prod --yes --token=$VERCEL_TOKEN
